package pyb.portfolio.feedscreener.miso;

// File generated by JavaTM Architecture for XML Binding (JAXB), v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// All modifications will be lost when regenerating the class from the XML schema.

import java.math.BigDecimal;
import java.sql.Timestamp;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

import lombok.ToString;
import pyb.portfolio.jaxb.adapter.TimestampAdapter;

/**
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ExAnteLMP">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Hub" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="LMP" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="loss" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                           &lt;attribute name="congestion" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="HourAndMin" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="RefId" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "exAnteLMP" })
@XmlRootElement(name = "LMPData")
@ToString
public class LMPData {

	@XmlElement(name = "ExAnteLMP", required = true)
	protected LMPData.ExAnteLMP exAnteLMP;
	@XmlAttribute(name = "RefId")
	@XmlSchemaType(name = "dateTime")
	@XmlJavaTypeAdapter(TimestampAdapter.class)
	protected Timestamp refId;

	public LMPData.ExAnteLMP getExAnteLMP() {
		return exAnteLMP;
	}

	public void setExAnteLMP(LMPData.ExAnteLMP value) {
		this.exAnteLMP = value;
	}

	public Timestamp getRefId() {
		return refId;
	}

	public void setRefId(Timestamp value) {
		this.refId = value;
	}

	/**
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="Hub" maxOccurs="unbounded">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;attribute name="LMP" type="{http://www.w3.org/2001/XMLSchema}decimal" />
	 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="loss" type="{http://www.w3.org/2001/XMLSchema}decimal" />
	 *                 &lt;attribute name="congestion" type="{http://www.w3.org/2001/XMLSchema}decimal" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *       &lt;attribute name="HourAndMin" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "hub" })
	@ToString
	public static class ExAnteLMP {

		@XmlElement(name = "Hub", required = true)
		protected List<LMPData.ExAnteLMP.Hub> hub;
		@XmlAttribute(name = "HourAndMin")
		@XmlSchemaType(name = "dateTime")
		protected XMLGregorianCalendar hourAndMin;

		/**
		 * Gets the value of the hub property.
		 *
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot.
		 * Therefore any modification you make to the returned list will be present
		 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
		 * for the hub property.
		 *
		 * <p>
		 * For example, to add a new item, do as follows:
		 *
		 * <pre>
		 * getHub().add(newItem);
		 * </pre>
		 *
		 *
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link LMPData.ExAnteLMP.Hub }
		 *
		 *
		 */
		public List<LMPData.ExAnteLMP.Hub> getHub() {
			if (hub == null) {
				hub = new ArrayList<>();
			}
			return this.hub;
		}

		public XMLGregorianCalendar getHourAndMin() {
			return hourAndMin;
		}

		public void setHourAndMin(XMLGregorianCalendar value) {
			this.hourAndMin = value;
		}

		/**
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;attribute name="LMP" type="{http://www.w3.org/2001/XMLSchema}decimal" />
		 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="loss" type="{http://www.w3.org/2001/XMLSchema}decimal" />
		 *       &lt;attribute name="congestion" type="{http://www.w3.org/2001/XMLSchema}decimal" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		@ToString
		public static class Hub {

			@XmlAttribute(name = "LMP")
			protected BigDecimal lmp;
			@XmlAttribute(name = "name")
			protected String name;
			@XmlAttribute(name = "loss")
			protected BigDecimal loss;
			@XmlAttribute(name = "congestion")
			protected BigDecimal congestion;

			public BigDecimal getLMP() {
				return lmp;
			}

			public void setLMP(BigDecimal value) {
				this.lmp = value;
			}

			public String getName() {
				return name;
			}

			public void setName(String value) {
				this.name = value;
			}

			public BigDecimal getLoss() {
				return loss;
			}

			public void setLoss(BigDecimal value) {
				this.loss = value;
			}

			public BigDecimal getCongestion() {
				return congestion;
			}

			public void setCongestion(BigDecimal value) {
				this.congestion = value;
			}
		}

	}

}
